services:
  envoy:
    volumes:
        - ./Ingress:/etc/envoy
    ports:
        - "10000:10000"
        - "9901:9901"

  aggregator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:2000
      - ProductApi=http://products:5000/
      - StoreApi=http://store:600/
    ports:
      - "2000:2000"

  orders:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:4000
      - SqlConnection=Data Source=sqlserver;Database=Orders;User Id=sa;Password="m1Password[12J";
    ports:
      - "4000:4000"


  products:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "5000:5000"

  store:
    environment:
        - FLASK_APP=app.py
        - FLASK_ENV=development
    ports:
      - "600:600"

  # Only for inspect data
  mongodb:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
 
  sqlserver:
    ports:
        - 1433:1433
    environment:
        SA_PASSWORD: "m1Password[12J"
        ACCEPT_EULA: "Y"
    mem_limit: 4G

  # OpenTelemetry
  zipkin:
    ports:
    - 9411:9411